USE comics;
INSERT INTO issues (title, type, number, event, reading_order) VALUES 
("X-Men: Messiah Complex","One-Shot", 1, "Messiah Complex", 1),
("Uncanny X-Men", "X-Men", 492, "Messiah Complex", 2),
("X-Factor","X-Men", 25, "Messiah Complex", 3),
("New X-Men","X-Men", 44, "Messiah Complex", 4),
("X-Men","X-Men", 205, "Messiah Complex", 5),
("Uncanny X-Men","X-Men", 493, "Messiah Complex", 6),
("X-Factor","X-Men", 26, "Messiah Complex", 7),
("New X-Men","X-Men", 45, "Messiah Complex", 8),
("X-Men","X-Men", 206, "Messiah Complex", 9),
("Uncanny X-Men","X-Men", 494, "Messiah Complex", 10),
("X-Factor","X-Men", 27, "Messiah Complex", 11),
("New X-Men","X-Men", 46, "Messiah Complex", 12),
("X-Men","X-Men", 207, "Messiah Complex", 13),
("X-Men: Messiah Complex - Mutant Files","One-Shot", 1, "Messiah Complex", 14),
("Avengers: X-Sanction", "Avengers", 1, "Avengers vs X-Men", 1),
("Avengers: X-Sanction", "Avengers", 2, "Avengers vs X-Men", 2),
("Avengers: X-Sanction", "Avengers", 3, "Avengers vs X-Men", 3),
("Avengers Academy", "Avengers", 26, "Avengers vs X-Men", 4)
("Avengers", "Avengers", 24, "Avengers vs X-Men", 5),
("Avengers: X-Sanction", "Avengers", 4, "Avengers vs X-Men", 6),
("Avengers vs X-Men", "Limited Series", 0, "Avengers vs X-Men", 7),
("Avengers vs X-Men", "Limited Series", 1, "Avengers vs X-Men", 8),
("Uncanny X-Men", "X-Men", 10, "Avengers vs X-Men", 9),
("Wolverine & The X-Men", "X-Men", 9, "Avengers vs X-Men", 10),
("Avengers", "Avengers", 25, "Avengers vs X-Men", 11),
("New Avengers", "Avengers", 24, "Avengers vs X-Men", 12),
("Avengers vs X-Men", "Limited Series", 2, "Avengers vs X-Men", 13),
("Avengers vs X-Men: Versus", "Limited Series", 1, "Avengers vs X-Men", 14),
("Uncanny X-Men", "X-Men", 11, "Avengers vs X-Men", 15),
("Secret Avengers", "Avengers", 26, "Avengers vs X-Men", 16),
("New Avengers", "Avengers", 25, "Avengers vs X-Men", 17),
("Avengers Academy", "Avengers", 29, "Avengers vs X-Men", 18),
("Avengers vs X-Men", "Limited Series", 3, "Avengers vs X-Men", 19),
("Wolverine & The X-Men", "X-Men", 10, "Avengers vs X-Men", 20),
("New Avengers", "Avengers", 26, "Avengers vs X-Men", 21),
("Uncanny X-Men", "X-Men", 12, "Avengers vs X-Men", 22),
("Avengers Academy", "Avengers", 30, "Avengers vs X-Men", 23),
("Avengers", "Avengers", 26, "Avengers vs X-Men", 24),
("Avengers", "Avengers", 27, "Avengers vs X-Men", 25),
("Avengers vs X-Men", "Limited Series", 4, "Avengers vs X-Men", 26),
("Avengers vs X-Men: Versus", "Limited Series", 2, "Avengers vs X-Men", 27),
("Wolverine & The X-Men", "X-Men", 11, "Avengers vs X-Men", 28),
("Secret Avengers", "Avengers", 27, "Avengers vs X-Men", 29),
("X-Men Legacy", "X-Men", 266, "Avengers vs X-Men", 30),
("X-Men Legacy", "X-Men", 267, "Avengers vs X-Men", 31),
("Uncanny X-Men", "X-Men", 13, "Avengers vs X-Men", 32),
("Avengers Academy", "Avengers", 31, "Avengers vs X-Men", 33),
("Avengers vs X-Men", "Limited Series", 5, "Avengers vs X-Men", 34),
("Avengers vs X-Men: Versus", "Limited Series", 3, "Avengers vs X-Men", 35),
("X-Men Legacy", "X-Men", 268, "Avengers vs X-Men", 36),
("Uncanny X-Men", "X-Men", 14, "Avengers vs X-Men", 37),
("Avengers Academy", "Avengers", 32, "Avengers vs X-Men", 38),
("Secret Avengers", "Avengers", 28, "Avengers vs X-Men", 39),
("New Avengers", "Avengers", 27, "Avengers vs X-Men", 40),
("Avengers vs X-Men", "Limited Series", 6, "Avengers vs X-Men", 41),
("Avengers vs X-Men: Versus", "Limited Series", 4, "Avengers vs X-Men", 42),
("Avengers", "Avengers", 28, "Avengers vs X-Men", 43),
("Uncanny X-Men", "X-Men", 15, "Avengers vs X-Men", 44),
("Wolverine & The X-Men", "X-Men", 12, "Avengers vs X-Men", 45),
("Avengers", "Avengers", 29, "Avengers vs X-Men", 46),
("Avengers vs X-Men", "Limited Series", 7, "Avengers vs X-Men", 47),
("Avengers vs X-Men: Versus", "Limited Series", 5, "Avengers vs X-Men", 48),
("Uncanny X-Men", "X-Men", 16, "Avengers vs X-Men", 49),
("Uncanny X-Men", "X-Men", 17, "Avengers vs X-Men", 50),
("Wolverine & The X-Men", "X-Men", 13, "Avengers vs X-Men", 51),
("New Avengers", "Avengers", 28, "Avengers vs X-Men", 52),
("New Avengers", "Avengers", 29, "Avengers vs X-Men", 53),
("Wolverine & The X-Men", "X-Men", 14, "Avengers vs X-Men", 54),
("Avengers vs X-Men", "Limited Series", 8, "Avengers vs X-Men", 55),
("Avengers Academy", "Avengers", 33, "Avengers vs X-Men", 56),
("Avengers Academy", "Avengers", 34, "Avengers vs X-Men", 57),
("Avengers vs X-Men", "Limited Series", 9, "Avengers vs X-Men", 58),
("Avengers vs X-Men", "Limited Series", 10, "Avengers vs X-Men", 59),
("Wolverine & The X-Men", "X-Men", 15, "Avengers vs X-Men", 60),
("Wolverine & The X-Men", "X-Men", 16, "Avengers vs X-Men", 61),
("Avengers vs X-Men", "Limited Series", 11, "Avengers vs X-Men", 62),
("New Avengers", "Avengers", 30, "Avengers vs X-Men", 63),
("Avengers vs X-Men", "Limited Series", 12, "Avengers vs X-Men", 64),
("Wolverine & The X-Men", "X-Men", 18, "Avengers vs X-Men", 65),
("Avengers vs X-Men: Versus", "Limited Series", 6, "Avengers vs X-Men", 66),
("Uncanny X-Men", "X-Men", 18, "Avengers vs X-Men", 67),
("Uncanny X-Men", "X-Men", 19, "Avengers vs X-Men", 68),
("Avengers", "Avengers", 30, "Avengers vs X-Men", 69),
("AvX: Consequences", "Limited Series", 1, "Avengers vs X-Men", 70),
("AvX: Consequences", "Limited Series", 2, "Avengers vs X-Men", 71),
("AvX: Consequences", "Limited Series", 3, "Avengers vs X-Men", 72),
("AvX: Consequences", "Limited Series", 4, "Avengers vs X-Men", 73),
("AvX: Consequences", "Limited Series", 5, "Avengers vs X-Men", 74),
("Thor", "Avengers", 80, "Disassembled", 1),
("Thor", "Avengers", 81, "Disassembled", 2),
("Thor", "Avengers", 82, "Disassembled", 3),
("Thor", "Avengers", 83, "Disassembled", 4),
("Thor", "Avengers", 84, "Disassembled", 5),
("Thor", "Avengers", 85, "Disassembled", 6),
("Iron Man", "Avengers", 84, "Dissembled", 7),
("Iron Man", "Avengers", 85, "Dissembled", 8),
("Spectacular Spider-Man", "Avengers", 15, "Disassembled", 9),
("Spectacular Spider-Man", "Avengers", 16, "Disassembled", 10),
("Spectacular Spider-Man", "Avengers", 17, "Disassembled", 11),
("Spectacular Spider-Man", "Avengers", 18, "Disassembled", 12),
("Spectacular Spider-Man", "Avengers", 19, "Disassembled", 13),
("Spectacular Spider-Man", "Avengers", 20, "Disassembled", 14),
("Captain America & The Falcon", "Avengers", 5, "Dissaemble", 15),
("Captain America & The Falcon", "Avengers", 6, "Dissaemble", 16),
("Captain America & The Falcon", "Avengers", 7, "Dissaemble", 17),
("Captain America", "Avengers", 29, "Disassembled", 18),
("Avengers", "Avengers", 500, "Disassembled", 19),
("Iron Man", "Avengers", 86, "Disassembled", 20),
("Avengers", "Avengers", 501, "Disassembled", 21),
("Avengers", "Avengers", 502, "Disassembled", 22),
("Captain America", "Avengers" 30, "Disassembled", 23),
("Captain America", "Avengers" 31, "Disassembled", 24),
("Captain America", "Avengers" 32, "Disassembled", 25),
("Avengers", "Avengers", 503, "Disassembled", 26),
("Iron Man", "Avengers", 87, "Disassembled", 27),
("Iron Man", "Avengers", 88, "Disassembled", 28),
("Iron Man", "Avengers", 89, "Disassembled", 29),
("Avengers Finale", "Avengers", 1, "Disassembled", 30),
("Fantastic Four", "Avengers", 517, "Disassembled", 31),
("Fantastic Four", "Avengers", 518, "Disassembled", 32),
("Fantastic Four", "Avengers", 519, "Disassembled", 33);